export const WRITE_WIZARD_1 = 'WRITE_WIZARD_1';
export const WRITE_WIZARD_2 = 'WRITE_WIZARD_2';
export const WRITE_WIZARD_3 = 'WRITE_WIZARD_3';
export const WRITE_WIZARD_4 = 'WRITE_WIZARD_4';
export const WRITE_WIZARD_5 = 'WRITE_WIZARD_5';
export const WRITE_LOAN_FIELD = 'WRITE_LOAN_FIELD';
export const WRITE_MORTGAGE_FIELD = 'WRITE_MORTGAGE_FIELD';
export const RESET_STORE = 'RESET_STORE';
